### ISSUE TITLE
oAuth User is not stored in db

### ISSUE THREAD

**Issue by janikvonrotz** [nicolaslopezj/meteor-apollo-accounts#10]
I've added a social login to my app. The oAuth login process seems to work, but the user account is not stored in the database. In the end the result set of the client loginWith... function is empty.

Here's the branch: https://github.com/janikvonrotz/meteor-apollo-accounts-example/tree/social-login

**Comment by nicolaslopezj** [comment]
You where having an error in ```Accounts.onCreateUser``` and the error was not thrown, now the error throws but you have to fix it.

This will help:

```js
if (user.services.google) {
  user.emails = [{ address: user.services.google.email, verified: true }]
}

if (user.services.facebook) {
  user.emails = [{ address: user.services.facebook.email, verified: true }]
}
```

**Comment by janikvonrotz** [comment]
Thank you very much, it worked!
