### ISSUE TITLE
Include packages with import

### ISSUE THREAD

**Issue by janikvonrotz** [nicolaslopezj/meteor-apollo-accounts#11]
I've seen that you are using global.* to include packages. Why not using import? This PR is not working, it's just an exmaple.

Example: `import HTTP from 'meteor/http` instead of `var HTTP = global.HTTP`

The advantage of this, is that Meteor knows what package is missing. I ran into many times while updating my example app.

```
I got messages like: 1114-12:33:06.212(1)? (STDERR) TypeError: Cannot read property 'secret' of undefined
1114-12:33:06.214(1)? (STDERR) at module.export.exports.default (packages/nicolaslopezj:apollo-accounts/src/Res
s/oauth/resolver.js:11:29)
```

And the solution was to add the missing package.

**Comment by nicolaslopezj** [comment]
I didn't wanted to make the package depend on all to make optional to have password, google or facebook. People opt in by doing meteor add accounts-facebook.

But all non accounts-* could be added to dependencies to solve this problem

**Comment by janikvonrotz** [comment]
Ah I see, but now my package file looks like this:

```
nicolaslopezj:apollo-accounts
accounts-password@1.3.2
apollo
accounts-facebook
accounts-google
facebook
google
http
random
oauth
```

Would it work with a check `hasService('facebook')` and then a require import `var HTTP = require('meteor/http)`? 

It's important to me that my package file is small like this:

```
nicolaslopezj:apollo-accounts
accounts-password@1.3.2
apollo
accounts-facebook
accounts-google
```

**Comment by nicolaslopezj** [comment]
But all non accounts-* could be added to *apollo-accounts package* dependencies to solve this problem
