### ISSUE TITLE
Using meteor-apollo-accounts to secure pages

### ISSUE THREAD

**Issue by dbrrt** [nicolaslopezj/meteor-apollo-accounts#13]
Hi was just wondering how to use this package to secure components views ?
For example, a logged user will have access to a page and not another one if not logged.
Should we use something like the "me" variable in the ApolloClient, fetching data from gql server and checking it before mounting the Component View or there's something more elegant?

**Comment by janikvonrotz** [comment]
I thought about that myself.
The solution you proposed is the current way to go, but I agree with you, it is not very elegant.
Another more elegant solution I thought of would be a method provided by the package, that simply stores or retrieves the user object.

```
import { getCurrentUser, setCurrentUser } from 'meteor-apollo-accounts'
```

The `setCurrentUser` method could be called inside a parent component that only loads child components when the user has been stored.

**Comment by dbrrt** [comment]
I can't figure out where are these methods,
In the index.js file of the meteor-apollo-accounts, they don't appear 
```
export {
  changePassword,
  createUser,
  forgotPassword,
  getLoginToken,
  hashPassword,
  loginWithPassword,
  logout,
  resendVerificationEmail,
  resetPassword,
  verifyEmail,
  loginWithFacebook,
  loginWithGoogle,
  onTokenChange
}
```

But yes, that would be a clean way to go.

**Comment by janikvonrotz** [comment]
@dbrrt have a look at https://github.com/nicolaslopezj/roles
Would be great to to see similar named queries and mutations.

**Comment by dbrrt** [comment]
That's just a matter of time, I really like how Nicolas wrote these queries and mutations to be reused as functions, I'll do on the same way, but I'd like to implement roles differently.
Thanks for the link btw!

**Comment by dbrrt** [comment]
I tested userId(), it works flawlessly, but the component needs to be loaded first to check if the user is logged (at least in React). I'd like to implement a mechanism like a 'wait On Data' before displaying the secured view/component. I think mounting another component waiting that the data is ready to mount another component in callback is one solution, but maybe there are better ones? Thanks for your work and your examples, really helpful.

**Comment by nicolaslopezj** [comment]
Maybe you can check in the router. Which router are you using?

**Comment by dbrrt** [comment]
I'm using Iron:Router and react-mounter inside a mantra.js instance
Would React Router a better fit for this purpose ?

**Comment by nicolaslopezj** [comment]
React Router is better than iron router, but this package should not be for a router in specific.

You could check with ```userId()``` in an iron router hook and redirect the user if it's not logged in

**Comment by dbrrt** [comment]
The below example works great and was exactly what I was looking for , I hope this could help others,
it should even be a base example to secure React views.

`import React from 'react';
import {mount} from 'react-mounter';

import { ApolloClient, Homepage, Login } from './index';
import { ApolloProvider } from 'react-apollo'

import { Router, Route, browserHistory } from 'react-router'
import { userId } from '/lib/gql_accounts/Client_Methods'

// Hook where will be fetched the data before displaying the component
// Will redirect user if not logged
function requireAuth(nextState, replaceState) {
    if(!userId())
    {
      replaceState("/login")
    }
}


const MainComponent = React.createClass({
  render() {
    return (
      <div>
        <ApolloProvider client={ApolloClient}>
          <Router history={browserHistory}>
           <Route>
             <Route path="/" onEnter={requireAuth} component={Homepage} />
             <Route path="/login" component={Login} />
           </Route>
         </Router>
       </ApolloProvider>
      </div>
    );
  }
});


Meteor.startup(() => {
  mount(MainComponent);
});`

**Comment by janikvonrotz** [comment]
@dbrrt Thank you for this solution. I've added it to my example app, works great.

https://github.com/janikvonrotz/meteor-apollo-accounts-example/commit/0b2f1d8268b2bf40e2658e8a137bdb8d544b0d3a

**Comment by acomito** [comment]
I have a similar requirement but it would need to be based on a role not just if the user is logged in... any ideas?
