### ISSUE TITLE
createUser with profile

### ISSUE THREAD

**Issue by sweetcharity** [nicolaslopezj/meteor-apollo-accounts#15]
Could you add support to create user with profile object? Object with just one string field would be fine

**Comment by sweetcharity** [comment]
so we can stringify any object, put the result in the string field of profile object, mutate "createUser", than parse this field with Accounts.onCreateUser() on server

**Comment by nicolaslopezj** [comment]
Do you want to do this @janikvonrotz?

**Comment by nicolaslopezj** [comment]
I don't like the idea of giving the ability to pass anything, maybe we could create a configuration in the server for:

```graphql
type Mutation {
  createUser (username: String, email: String, password: HashedPassword!, profile: CreateUserProfileInput): LoginMethodResponse
}

input CreateUserProfileInput {
  
}
```

**Comment by janikvonrotz** [comment]
Good idea, I'll do it

**Comment by nicolaslopezj** [comment]
Design ideas:

```js
import {SchemaTypes as Auth} from 'meteor/nicolaslopezj:apollo-accounts'
import Query from './Query.graphql'
import Mutation from './Mutation'

export default [
  Auth,
  Query,
  Mutation({
    profileInput: "name: String! bio: String"
  })
]
```
