### ISSUE TITLE
Storing profile data in Apollo store once user is logged?

### ISSUE THREAD

**Issue by dbrrt** [nicolaslopezj/meteor-apollo-accounts#19]
I don't really know if that's feasible (since I don't really understand how "id" has been set on server) : 
I'd like to store profile data in the Apollo Store, once the user has been successfully logged.
The LoginResponse schema fetch **id**, **token** and **tokenExpires** but it'd be also interesting in some cases to have profile data reachable, so is that possible to add as an extra parameter in LoginResponse schema, user profile as **profile: UserProfile**, and storing it as an Object in "global.localStorage['Meteor.profile']" for instance?
Then it would be really easy to grab anything like username, firstname, lastname and other things corresponding to the Meteor user.
In other hand, that could cause side effects with **Oauth services**... So I don't know if that's a good idea to implement something like that. Or simply, once the user is logged, getting profile data in a callback function?

**Comment by janikvonrotz** [comment]
There is a PR with the option to inject a UserProfile: https://github.com/nicolaslopezj/meteor-apollo-accounts/pull/16/files.

If set we could extend the LoginResponse schema with a profile property.

Should not be a problem when working with Oauth services. You only have to set the properties yourself. Reference: https://github.com/janikvonrotz/meteor-apollo-accounts-example/blob/master/server/account.js

**Comment by barrada3** [comment]
Ok, great, that's exactly what I needed.

**Comment by dbrrt** [comment]
Ok, great, that's exactly what I needed.

**Comment by dbrrt** [comment]
So will the LoginResponse schema will be updated with UserProfile options ?

**Comment by nicolaslopezj** [comment]
@dbrrt check #23
