### ISSUE TITLE
loginWithPassword and other mutations return null

### ISSUE THREAD

**Issue by janikvonrotz** [nicolaslopezj/meteor-apollo-accounts#22]
My setup: https://github.com/janikvonrotz/meteor-apollo-accounts-example/tree/bug/nullreturn

Now when I try:

```
mutation{
  loginWithPassword(email: "admin@example.com", plainPassword: "password")	{
    id
    token
    tokenExpires
  }
}
```

it returns

```
{
  "data": {
    "loginWithPassword": null
  }
}
```

The user exist and no other errors are thrown.

Of course I tried to debug it, but was not successful.

**Comment by dbrrt** [comment]
Is "passsword" a typo ?
I'll try to reproduce this case.

Do you think that we'll be able soon to do something like : 
```
  loginWithPassword(email: "admin@example.com", plainPassword: "passsword")	{
    id
    token
    tokenExpires
    profile
  }

```
?

**Comment by nicolaslopezj** [comment]
Hmm very strange @janikvonrotz... It's ok in my app. It's the password with 3 s?

**Comment by janikvonrotz** [comment]
Password with 3 s was a typo, but didn't solve the error.

**Comment by janikvonrotz** [comment]
Forgot to turn the resolver spread into a function.
This `...Resolvers` into `...Resolvers()`.
