### ISSUE TITLE
Resolvers is not a fonction 

### ISSUE THREAD

**Issue by HBCharles** [nicolaslopezj/meteor-apollo-accounts#24]
After updating the package to the latest version and updating all the spread operators to fonctions the project couldnt work. Im having an error in the chrome console telling me that "resolvers" is not à fonction. 

Is there anything else to do to upgrade from the previous version of the package ?

**Comment by janikvonrotz** [comment]
Can you share the lines of code where the error is thrown?
Have updated both, the npm package and meteor package?

**Comment by HBCharles** [comment]
Both npm package (1.3.0) and meteor package (2.1.0) is updated. I just uninstall them and install again but still have the issue.

Lines of code concerned : 

**resolvers.js**
```
import { Meteor } from 'meteor/meteor';
import { Resolvers } from 'meteor/nicolaslopezj:apollo-accounts'

const usersResolvers = {
	Query: {
		me (roott, args, context) {
			const { userId } = context ? context : { userId: null };
			if (userId)
			return Meteor.users.findOne({ _id: userId });
		},
		users (root, args) {
			return Meteor.users.find().fetch();
		}
	},
	Mutation: {
		...Resolvers()
	}
};

export default usersResolvers;

```

**Error message in Chrome console**
![image](https://cloud.githubusercontent.com/assets/9991267/21081398/ec2d9f74-bfc5-11e6-95c4-f5cc7eeae486.png)

**Comment by HBCharles** [comment]
Finally got it working just by deplacing my schema, server side instead of lib.
