### ISSUE TITLE
Naming libs

### ISSUE THREAD

**Issue by dbrrt** [nicolaslopezj/meteor-apollo-accounts#27]
Not really a functionnal issue, but I think that the package/lib naming is a bit confusing : 
- **meteor-apollo-accounts** could be replaced with something like **apollo-accounts-client**, since it's working on potentially any front-end client with React and Apollo running, (including React-native)
- **apollo-accounts** could be replaced with something like **apollo-accounts-server**

**Comment by nicolaslopezj** [comment]
Cloud just change folder name work? Changing the name of the packages will be complicated

**Comment by dbrrt** [comment]
Yes of course. At least this way it'll be way more understandable for people that'll clone the package to understand the context of both libraries.
