### ISSUE TITLE
Package not working after updating to 2.2.1

### ISSUE THREAD

**Issue by HBCharles** [nicolaslopezj/meteor-apollo-accounts#28]
I couldn't access the userId after authentification since the update to 2.2.1

I also tried with https://github.com/janikvonrotz/meteor-apollo-accounts-example

**Comment by dbrrt** [comment]
The reason is certainly the following line in store.js
` set: async function ({userId, token, tokenExpires}) `
If fixed it locally but didn't pushed the version last version. My bad...

**Comment by dbrrt** [comment]
Could you be more specific on what's not working ? Are you using React native or React ?

**Comment by HBCharles** [comment]
I'm using React v15.4.0 and trying to obtain the userId from the context in the query resolver :

```
const usersResolvers = {
	Query: {
		me (root, args, context) {
			const { userId } = context;
			return Meteor.users.findOne({ _id: userId });
		},
```
and from the package. 

```
import { userId } from 'meteor-apollo-accounts'

const usersResolvers = {
	Query: {
		me (root, args, context) {
			return Meteor.users.findOne({ _id: userId() });
		},

```

Both don't work.

**Comment by dbrrt** [comment]
It was because of the keywords 'async' and 'await' are not suitable in this context, works with AsyncStorage, but won't with localStorage, 
With async/await on getUserId() I get 
Promise { <state>: "pending" } instead of the userId string
 and without : 
q3oeKqdENCTL6Mx8A, which is my userId(), I'll push the fix soon.

Tested on React Native and React 15, both work.
Thanks for submitting the bug.

**Comment by nicolaslopezj** [comment]
You must do
```js
const id = await userId()
```

**Comment by dbrrt** [comment]
@nicolaslopezj Thanks for the tip.
It depends if the function that'll get the data is or not wrapped with async/await.

In the case of localStorage, we shouldn't use async/await, because HTML5 localStorage is a synchronous blocking API.

AsyncStorage is asynchronous, so async/await is required.

**Comment by nicolaslopezj** [comment]
But how the package would know if its using async? Its better to always use async

**Comment by dbrrt** [comment]
@nicolaslopezj At least, this can do the job in most cases, if the documentation shows how to use it from any plateform, no one will complain on it.

**Comment by nicolaslopezj** [comment]
I updated the docs to async. Please notify if you see errors
