### ISSUE TITLE
Create example app

### ISSUE THREAD

**Issue by nicolaslopezj** [nicolaslopezj/meteor-apollo-accounts#3]
Create a example app:
- Meteor server side
- Create react app client side

**Comment by nicolaslopezj** [comment]
Server side app created

**Comment by janikvonrotz** [comment]
https://github.com/janikvonrotz/meteor-apollo-accounts-example

It doesn't work yet. I would like to know if you like my idea. I usually don't separate the client and server, it makes things a lot easier.

I have a two more questions:
* the resolver doesn't know userId, did I miss somehting?
* Would be possible to make the login function in a promise style?

```
TypeError: Cannot read property 'userId' of undefined
  at me (meteor://app/server/resolvers.js:6:29)
```

**Comment by nicolaslopezj** [comment]
I love your idea. I know a **lot** of people doesn't separate client and server, especially in meteor.

> the resolver doesn't know the userId, did I miss somehting?

Did you config the apollo to receive the meteor token and set the userId in the context? Thats what meteor package ```apollo``` do.

> Would it be possible to make the login function in a promise style?

It is a promise style function, just like apollo mutations. You can use it like this:

```js
async function submit () {
  await login({})
}
```

**Comment by janikvonrotz** [comment]
Hey Nicolas,
I fixed a few [things](https://github.com/janikvonrotz/meteor-apollo-accounts-example). You were right with the `apollo` package.
Some issues I have to solve and might need your attention:

*  LoginWithPassword and Logout should execute the callback.
* LoginWithPassword and Logout function force a browser reload.
* This error: `TypeError: Cannot read property 'userId' of undefined  at me (meteor://app/server/resolvers.js:6:30)`, I don't even access the userId on this line of code.

**Comment by janikvonrotz** [comment]
Another question. Would you like to showcase your package and the example app on the Meteor forums? Of course first I have to fix the issues mentioned and make it a bit more useful.

**Comment by nicolaslopezj** [comment]
> LoginWithPassword and Logout should execute the callback.

I made a PR in your repo

> LoginWithPassword and Logout function force a browser reload.

Yes, I don't like that but I can't find a way to reload all "active" queries.

> This error: TypeError: Cannot read property 'userId' of undefined at me (meteor://app/server/resolvers.js:6:30), I don't even access the userId on this line of code.

I think the context is not set if there is no userId, so first check if there is context.

> Another question. Would you like to showcase your package and the example app on the Meteor forums? Of course first I have to fix the issues mentioned and make it a bit more useful.

Of course! I'm waiting till this package is polished.

**Comment by janikvonrotz** [comment]
Thanks a lot 😄 

> > LoginWithPassword and Logout function force a browser reload.

> Yes, I don't like that but I can't find a way to reload all "active" queries.

For now I would remove the reload. Moreover, I don't think you have to reload the queries. I propose that one can decide for himself what to do next after a successful login or log out. For example you can:

* Reload the browser
* Dispatch a redux action which would trigger a reload (I don't really know how this works)
* Redirect to another page (and do the refetch there)
* Refetch the queries on the current component
* Flush whatever local store you are using

**Comment by nicolaslopezj** [comment]
You're right. I'll remove the reload.

**Comment by janikvonrotz** [comment]
What other features would you like to see?

* Extend the example with a full user register and verification process using react-router.
* React-router redirection
* Styling with components (I love material-ui)

Or can I help you with package itself?

**Comment by nicolaslopezj** [comment]
All three if you can!

**Comment by janikvonrotz** [comment]
Thanks for your help 😃 I've updated the demo app with a few more features. Would be nice to showcase the stuff on the meteor forum soon.

**Comment by nicolaslopezj** [comment]
Great @janikvonrotz. The example you made is great. I'm sure it will help a lot of people.
