### ISSUE TITLE
Error on mutation / loginWithPassword

### ISSUE THREAD

**Issue by dbrrt** [nicolaslopezj/meteor-apollo-accounts#40]
Hello,
I got this error using  loginWithPassword with the last version of this package 

`Error: Network error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Stacktrace :
ApolloError@http://localhost:3000/packages/modules.js?hash=ef09dcb3c23d04ed293f67d0e02e2fade2789941:33962:23
require<.node_modules["apollo-client"].core["QueryManager.js"]</QueryManager</QueryManager.prototype.mutate/</<@http://localhost:3000/packages/modules.js?hash=ef09dcb3c23d04ed293f67d0e02e2fade2789941:33338:24
Meteor.bindEnvironment/<@http://localhost:3000/packages/meteor.js?hash=e3f53db3be730057fed1a5f709ecd5fc7cae1229:1105:17`

Anyone has been able to use it ?

Note that this doesn't work neither with React-Native (in my configuration)

**Comment by nicolaslopezj** [comment]
What is in that line? Can you show more details? I'm not getting this error

**Comment by dbrrt** [comment]
It was "Error : ", but I suppose an incompatibility bewteen packages (on my projects), it'd be nice to update Janik's example with the later version of the library and right dependencies. I'll try to fix that as soon as possible.

**Comment by nicolaslopezj** [comment]
You could make a PR to his repo

**Comment by dbrrt** [comment]
I solved this, by using your ApolloCreateServer, weird, but it works now.
