### ISSUE TITLE
LoginMethodResponse type is missing

### ISSUE THREAD

**Issue by janikvonrotz** [nicolaslopezj/meteor-apollo-accounts#5]
Hi, I just wanted to setup an example application for you. https://github.com/janikvonrotz/meteor-apollo-accounts-example
But then I got this message:
```
Error: Type "LoginMethodResponse" not found in document.
W20161018-21:27:24.729(-7)? (STDERR)     at typeDefNamed (C:\Users\janikvonrotz\Documents\GitHub\meteor-apollo-accounts-example\node_modules\graphql\utilities\buildASTSchema.js:
```
I assume this is one of the response types you are using in your meteor accounts schema. Could you update the meteor package?

**Comment by nicolaslopezj** [comment]
You are missing SchemaTypes:

```js
import {SchemaTypes as Auth} from 'meteor/nicolaslopezj:apollo-accounts'
```

https://github.com/nicolaslopezj/meteor-apollo-accounts/blob/master/example/meteor-server/server/imports/apollo/schema/typeDefs/index.js#L1

Please make a PR fixing the docs to make this more easy.

It's awesome that you are making an example!
