### ISSUE TITLE
Remove dependency on graphql-loader

### ISSUE THREAD

**Issue by dlredden** [nicolaslopezj/meteor-apollo-accounts#76]
I would love to use this in my project, but we don't use `graphql-loader`. It looks like one would be able to change `initAccounts` to return the typeDefs and resolvers for the caller to use in their project as they see fit. As it stands this projects forces a GraphQL implementation pattern which would be expected if this were a framework and not an auth wrapper.

**Comment by macrozone** [comment]
I saw graphql-loader here for the first time and i don't know why it is used. It seems not be used in the meteor apollo examples (but maybe i am wrong)

**Comment by nicolaslopezj** [comment]
Please make a pull request

**Comment by acomito** [comment]
What did you do here dlredden?

**Comment by dlredden** [comment]
I don't believe I ever got anything working and I moved on. The project I was working on stopped so I never had to complete the task.
