### ISSUE TITLE
 Error: Mutation.loginWithPassword defined in resolvers, but not in schema

### ISSUE THREAD

**Issue by janikvonrotz** [nicolaslopezj/meteor-apollo-accounts#8]
hey, I tried to upgrade to the latest version and got this error while building my demo app.

` Error: Mutation.loginWithPassword defined in resolvers, but not in schema`

I've checked the code, but probably missed something.

**Comment by janikvonrotz** [comment]
As reference: https://github.com/janikvonrotz/meteor-apollo-accounts-example

**Comment by janikvonrotz** [comment]
Thanks for the update, however, it's not working for me yet:

`Error: Mutation.createUser defined in resolvers, but not in schema`

**Comment by nicolaslopezj** [comment]
Remember that you have to install ```accounts-password```

**Comment by janikvonrotz** [comment]
I did so. It seems that the `hasService('password')` check is not working for me. Could you run the the demo app from **update** branch and tell me if it works for you?

If I run this code server-side:

````
const Package = global.Package

console.log(!!Package['accounts-password'], Package['accounts-password'])
```

I'll get this output:

```
true {}
```

So I'm not sure why it fails to load the right graphql mutations.

**Comment by janikvonrotz** [comment]
Is the second gql tag necessary? It probably works without.
````
export default gql`
${
  hasService('password') ? gql`...
```

**Comment by nicolaslopezj** [comment]
The tag doesn't do nothing, it's just for syntax highlighting.

What error are you having?

**Comment by janikvonrotz** [comment]
The schema is not parsed:

````
  # Log the user in with a password.
  loginWithPassword (username: String, email: String, password: HashedPassword, plainPassword: String): LoginMethodResponse

  # Create a new user.
  createUser (username: String, email: String, password: HashedPassword!): LoginMethodResponse

  # Change the current user's password. Must be logged in.
  changePassword (oldPassword: HashedPassword!, newPassword: HashedPassword!): SuccessResponse

  # Request a forgot password email.
  forgotPassword (email: String!): SuccessResponse

  # Reset the password for a user using a token received in email. Logs the user in afterwards.
  resetPassword (newPassword: HashedPassword!, token: String!): LoginMethodResponse
```
And I think its because of this:

```
export default gql`
${
  hasService('password') ? >>gql<<`
  # Log the user in with a password.
```

Maybe it works without the graphql tag:

```
export default gql`
${
  hasService('password') ? `
  # Log the user in with a password.
```

**Comment by nicolaslopezj** [comment]
Mmm I don't think it's the graphql tag, it works in my code. I believe that ```hasService('password')``` is returning false to you, but why? 🤔

**Comment by janikvonrotz** [comment]
I did a test: https://github.com/janikvonrotz/meteor-apollo-accounts-example/commit/53aa06c27defed43b186af4415ddd27ff55f00a3

I've added the mutations from your packages directly into my schema. It only works without the `gql` tags. The plain text schema is taken as parameter for `makeExecutableSchema`. So it is not necessary to parse the graphql schema definitions with the gql tag.

I suppose you remove the `gql` tag in your schema definitions. This would also work according to the apollo documentation: http://dev.apollodata.com/tools/graphql-tools/generate-schema.html 

Please let me know it this works for you.

**Comment by nicolaslopezj** [comment]
This is the gql tag I'm using https://github.com/nicolaslopezj/meteor-apollo-accounts/blob/master/apollo-accounts/src/gql.js
Not the package "graphql-tag". It doesn't do anything. 

The error must be somewhere else 🤔

**Comment by janikvonrotz** [comment]
But why use a parser at all?

**Comment by janikvonrotz** [comment]
Can you run the update branch of my demo app?

**Comment by nicolaslopezj** [comment]
Now it's fixed, just by adding accounts-password to the weak dependencies of this package.

**Comment by nicolaslopezj** [comment]
Thanks a lot for testing and making the example
